spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock?characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # \u903B\u8F91\u5DF2\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 1)
      logic-not-delete-value: 0 # \u903B\u8F91\u672A\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 0)
  configuration:
    map-underscore-to-camel-case: false # \u4E0D\u4F7F\u7528\u9A7C\u5CF0\u547D\u540D\u6CD5
server:
  port: 8080
logging:
  level:
    com.zxy.zxy.mapper: debug
